apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: nuit-isen
build:
  googleCloudBuild:
    projectId: nuit-isen
  artifacts:
  - image: us.gcr.io/nuit-isen/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: "***/*.ts"
        dest: .
  - image: us.gcr.io/nuit-isen/users
      context: users-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "***/*.ts"
            dest: .
  - image: us.gcr.io/nuit-isen/posts
      context: posts-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "***/*.ts"
            dest: .
# test:
deploy:
  kubectl:
    manifests:
    - infra/k8s/staging/*.yaml
    - infra/k8s/production/*.yaml
profiles:
- name: staging
  deploy:
    kubectl:
      manifests:
      - infra/k8s/*.yaml
      - infra/k8s/staging/*.yaml
- name: production
  deploy:
    kubectl:
      manifests:
      - infra/k8s/*.yaml
      - infra/k8s/production/*.yaml
